baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Site nul hihi'
theme = "PaperMod"
[params.homeInfoParams]
Title = "Salam les khouilla,  mhhhh je connais mon corp ..."

[[contentTypes]]
  name = "post"
  description = "Articles"
  layout = "post"
  draft = false

[[menu.main]]
identifier = "home"
name = "Accueil"
url = "/"

[[menu.main]]
identifier = "adrien"
name = "adrien"
url = "/adrien/"

[[menu.main]]
identifier = "antoine"
name = "Antoine"
url = "/antoine/"

[[menu.main]]
identifier = "thomas"
name = "thomas"
url = "/thomas/"

[[menu.main]]
identifier = "brandon"
name = "brandon"
url = "/brandon/"




