baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Site nul hihi'
theme = "PaperMod"
[params.homeInfoParams]
Title = "Site créé par Luca Grousset grâce à Hugo."
[[params.socialIcons]]
name = "github"
url = "https://github.com/lucag322/site-nul"

[[params.socialIcons]]
name = "other"
url = "https://lucagrousset.eu/"



[params.assets]
favicon = "<link /favicon.icon>"

[[socialIcons]]
name = "kofi"
title = "<custom title>"
url = "https://kofi.com"


[[contentTypes]]
  name = "post"
  description = "Articles"
  layout = "post"
  draft = false

[[menu.main]]
identifier = "home"
name = "Accueil"
url = "/"


[[menu.main]]
identifier = "search"
name = "search"
url = "/search/"

[[menu.main]]
identifier = "faq"
name = "FAQ"
url = "/faq/"


[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
ShowShareButtons = true
ShareButtons = [ "linkedin", "twitter" ]
ShowBreadCrumbs = true
ShowCodeCopyButtons = true




