baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Site nul hihi'
theme = "PaperMod"
[params.homeInfoParams]
Title = "Chroniques du Monde: Actualités et Perspectives Globales"

[[contentTypes]]
  name = "post"
  description = "Articles"
  layout = "post"
  draft = false

[[menu.main]]
identifier = "home"
name = "Accueil"
url = "/"


[[menu.main]]
identifier = "search"
name = "search"
url = "/search/"

[[menu.main]]
identifier = "faq"
name = "FAQ"
url = "/faq/"


[outputs]
home = [ "HTML", "RSS", "JSON" ]



